name: Test

permissions:
  contents: write

on: [push]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}
jobs:
  rust-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-latest, macos-14, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: ahaoboy/easy-setup@v1
        with:
          url: |-
           https://github.com/ahaoboy/txiki.js-build
           https://github.com/ahaoboy/easy-install/raw/refs/heads/main/dist-manifest/llrt.json
           https://github.com/ahaoboy/easy-install/raw/refs/heads/main/dist-manifest/quickjs-ng.json

      - name: test
        run: |
          which qjs
          which llrt
          which tjs

          echo "console.log(1)" >> a.js
          qjs a.js
          llrt a.js
          tjs run a.js